name: instagram_clone_app1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
 
  flutter:
    sdk: flutter
  cloud_firestore: ^3.4.8
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  firebase_database: ^9.1.4
  firebase_storage: ^10.3.8
  path_provider: ^2.0.11
  provider: ^6.0.3
  path: ^1.8.1
  flutterfire_ui: ^0.4.3+9
  flutter_screenutil: ^5.5.4
  image_picker: ^0.8.5+3
  flutter_svg: ^1.1.5
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  permission_handler: ^10.0.0
  freezed_annotation: ^2.1.0
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.6.2
  date_format: ^2.0.7
  flutter_local_notifications: ^12.0.2 
  dio: ^4.0.6
  firebase_messaging: ^13.1.0
  story_view: ^0.14.0
  get_it: ^7.2.0
  device_preview: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.2
  build_runner: ^2.2.1




  
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

  assets:
    - assets/images/111.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

 
  fonts:
    - family: Billabong
      fonts:
       - asset: assets/fonts/billbong.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
