// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTpEpG17TpnhVbOfMSYdIRVuWRk6Asa3g',
    appId: '1:41209341552:web:eb8d573b97d22920b3f6b5',
    messagingSenderId: '41209341552',
    projectId: 'instagramclone-e9815',
    authDomain: 'instagramclone-e9815.firebaseapp.com',
    storageBucket: 'instagramclone-e9815.appspot.com',
    measurementId: 'G-6Z2TN517NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARzT-EG7mEXftZcDAsx3kvwnR51_i5bJM',
    appId: '1:41209341552:android:557f2112f671f1bcb3f6b5',
    messagingSenderId: '41209341552',
    projectId: 'instagramclone-e9815',
    storageBucket: 'instagramclone-e9815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVDo5TlLcELFm0fM95qA6r9zUukBwI-0E',
    appId: '1:41209341552:ios:e3b450072c417234b3f6b5',
    messagingSenderId: '41209341552',
    projectId: 'instagramclone-e9815',
    storageBucket: 'instagramclone-e9815.appspot.com',
    iosClientId: '41209341552-fp0alvmi5d7kq1ntv1705pnh8iffn08f.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVDo5TlLcELFm0fM95qA6r9zUukBwI-0E',
    appId: '1:41209341552:ios:e3b450072c417234b3f6b5',
    messagingSenderId: '41209341552',
    projectId: 'instagramclone-e9815',
    storageBucket: 'instagramclone-e9815.appspot.com',
    iosClientId: '41209341552-fp0alvmi5d7kq1ntv1705pnh8iffn08f.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneApp1',
  );
}
